Revert "Move all `wasi:` packages over to a `wasiless:` namespace."
This reverts commit 970bd61c20fa078c5081c91ffdd7344754c65bb2.

This gambit didn't work. We were with the same error upon `wac`:
```
error: the encoding of the graph failed validation

Caused by:
    type mismatch for import `wasi:filesystem/types@0.2.0`
    type mismatch in instance export `input-stream`
    resource types are not the same (ResourceId { globally_unique_id: 2, contextually_unique_id: 124 } vs. ResourceId { globally_unique_id: 2, contextually_unique_id: 6 }) (at offset 0x291a051)
```