Add a wac file for satisfying Flask and Bottle's apps with wasiless' stubs.
Note both flask-app.wasm and wit-bottle.wasm have identical WIT (and thus imports), so one should link if the other does.

Current error:
```
% wac compose --dep fastly:wasiless=../wasiless/componentized.wasm --dep app:component=build/wit-bottle.wasm -o composed.wasm wrap_app_in_wasiless.wac
error: the encoding of the graph failed validation

Caused by:
    type mismatch for import `wasi:filesystem/types@0.2.0`
    type mismatch in instance export `input-stream`
    resource types are not the same (ResourceId { globally_unique_id: 2, contextually_unique_id: 134 } vs. ResourceId { globally_unique_id: 2, contextually_unique_id: 6 }) (at offset 0x2916624)
```